### ISSUE TITLE
Support for multiple servers?

### ISSUE THREAD

**Issue by n1nj4888** [barrycarey/Speedtest-for-InfluxDB-and-Grafana#12]
Would it be possible to include support for multiple servers in the python script?

This would be useful to test / report against the current ISP server and another remote server?

**Comment by skylord123** [comment]
Currently I know you can just add this docker twice to get what you want but you would also want them to not run at the same time (otherwise it would skew the results).

From the looks of it I think this could be accomplished pretty effortlessly. Just make the servers take a comma separated list that runs them in order.

**Comment by barrycarey** [comment]
Sorry for the delay.  I just pushed an update that includes support for multiple servers now.  You can use a comma separated list in the config
